/**
 * Replay Engine System
 * 
 * Handles match replays, video playback, clip generation,
 * highlight management, and replay analytics.
 */

// Types
export interface ReplayFrame {
  timestamp: number;
  gameState: any;
  events: ReplayEvent[];
}

export interface ReplayEvent {
  id: string;
  timestamp: number;
  type: 'goal' | 'tackle' | 'pass' | 'shot' | 'foul' | 'injury' | 'substitution' | 'formation_change';
  player: string;
  data: Record<string, any>;
  importance: number;
}

export interface Replay {
  id: string;
  userId: string;
  matchId: string;
  title: string;
  description: string;
  duration: number;
  frames: ReplayFrame[];
  events: ReplayEvent[];
  fileSize: number;
  videoUrl: string;
  thumbnailUrl: string;
  quality: 'sd' | 'hd' | '4k';
  fps: number;
  bitrate: number;
  createdAt: number;
  uploadedAt?: number;
  isPublic: boolean;
  views: number;
  likes: number;
  shares: number;
}

export interface Highlight {
  id: string;
  replayId: string;
  userId: string;
  title: string;
  description: string;
  startTime: number;
  endTime: number;
  duration: number;
  type: 'goal' | 'save' | 'tackle' | 'skill_move' | 'epic_moment' | 'fail';
  difficulty: 'easy' | 'medium' | 'hard';
  videoUrl: string;
  thumbnailUrl: string;
  autoGenerated: boolean;
  createdAt: number;
  isPublic: boolean;
  views: number;
  likes: number;
  shares: number;
  comments: HighlightComment[];
}

export interface HighlightComment {
  id: string;
  userId: string;
  username: string;
  content: string;
  timestamp: number;
  likes: number;
  replies: HighlightComment[];
}

export interface Clip {
  id: string;
  highlightId: string;
  userId: string;
  title: string;
  description: string;
  duration: number;
  startFrame: number;
  endFrame: number;
  videoUrl: string;
  thumbnailUrl: string;
  format: 'mp4' | 'webm' | 'gif';
  resolution: string;
  createdAt: number;
  expiresAt?: number;
  isPublic: boolean;
  views: number;
  likes: number;
  downloads: number;
}

export interface PlaybackSession {
  id: string;
  replayId: string;
  userId: string;
  currentFrame: number;
  currentTime: number;
  isPlaying: boolean;
  playbackSpeed: number;
  volume: number;
  subtitles: boolean;
  selectedTrack?: string;
  startedAt: number;
  totalWatchTime: number;
  viewedFrames: number[];
}

export interface ReplayAnalytics {
  replayId: string;
  totalViews: number;
  totalLikes: number;
  totalShares: number;
  avgWatchTime: number;
  completionRate: number;
  topViewers: Array<{ userId: string; watchTime: number }>;
  viewsByDate: Array<{ date: string; views: number }>;
  deviceBreakdown: Array<{ device: string; views: number }>;
  quality: Array<{ quality: string; views: number }>;
}

export interface HighlightAI {
  minIntensity: number;
  detectGoals: boolean;
  detectSaves: boolean;
  detectTackles: boolean;
  detectSkillMoves: boolean;
  minDuration: number;
  maxDuration: number;
}

// Replay Engine Service
export class ReplayEngineService {
  private replays: Map<string, Replay> = new Map();
  private highlights: Map<string, Highlight> = new Map();
  private clips: Map<string, Clip> = new Map();
  private playbackSessions: Map<string, PlaybackSession> = new Map();
  private analytics: Map<string, ReplayAnalytics> = new Map();
  private highlightAIConfigs: Map<string, HighlightAI> = new Map();

  constructor() {
    this.loadFromStorage();
  }

  // Replay Management
  createReplay(userId: string, replayData: Partial<Replay>): Replay {
    const replay: Replay = {
      id: `replay_${userId}_${Date.now()}`,
      userId,
      matchId: replayData.matchId || '',
      title: replayData.title || 'Match Replay',
      description: replayData.description || '',
      duration: replayData.duration || 0,
      frames: replayData.frames || [],
      events: replayData.events || [],
      fileSize: replayData.fileSize || 0,
      videoUrl: replayData.videoUrl || '',
      thumbnailUrl: replayData.thumbnailUrl || '',
      quality: replayData.quality || 'hd',
      fps: replayData.fps || 60,
      bitrate: replayData.bitrate || 5000,
      createdAt: Date.now(),
      isPublic: replayData.isPublic || false,
      views: 0,
      likes: 0,
      shares: 0
    };

    this.replays.set(replay.id, replay);
    this.analytics.set(replay.id, {
      replayId: replay.id,
      totalViews: 0,
      totalLikes: 0,
      totalShares: 0,
      avgWatchTime: 0,
      completionRate: 0,
      topViewers: [],
      viewsByDate: [],
      deviceBreakdown: [],
      quality: []
    });

    this.saveToStorage();
    return replay;
  }

  getReplay(replayId: string): Replay | undefined {
    return this.replays.get(replayId);
  }

  getReplays(userId: string): Replay[] {
    return Array.from(this.replays.values()).filter(r => r.userId === userId);
  }

  getPublicReplays(): Replay[] {
    return Array.from(this.replays.values()).filter(r => r.isPublic);
  }

  updateReplay(replayId: string, updates: Partial<Replay>): Replay | undefined {
    const replay = this.replays.get(replayId);
    if (replay) {
      Object.assign(replay, updates);
      this.saveToStorage();
    }
    return replay;
  }

  deleteReplay(replayId: string): boolean {
    const deleted = this.replays.delete(replayId);
    if (deleted) {
      this.analytics.delete(replayId);
      this.saveToStorage();
    }
    return deleted;
  }

  addFrame(replayId: string, frame: ReplayFrame): void {
    const replay = this.replays.get(replayId);
    if (replay) {
      replay.frames.push(frame);
      this.saveToStorage();
    }
  }

  getFrames(replayId: string, startTime?: number, endTime?: number): ReplayFrame[] {
    const replay = this.replays.get(replayId);
    if (!replay) return [];

    if (startTime === undefined && endTime === undefined) {
      return replay.frames;
    }

    return replay.frames.filter(f => 
      (!startTime || f.timestamp >= startTime) && 
      (!endTime || f.timestamp <= endTime)
    );
  }

  addEvent(replayId: string, event: ReplayEvent): void {
    const replay = this.replays.get(replayId);
    if (replay) {
      replay.events.push(event);
      // Sort by timestamp
      replay.events.sort((a, b) => a.timestamp - b.timestamp);
      this.saveToStorage();
    }
  }

  getEvents(replayId: string, type?: ReplayEvent['type']): ReplayEvent[] {
    const replay = this.replays.get(replayId);
    if (!replay) return [];

    if (type) {
      return replay.events.filter(e => e.type === type);
    }
    return replay.events;
  }

  // Highlight Management
  createHighlight(userId: string, highlightData: Partial<Highlight>): Highlight {
    const highlight: Highlight = {
      id: `highlight_${userId}_${Date.now()}`,
      replayId: highlightData.replayId || '',
      userId,
      title: highlightData.title || 'Highlight',
      description: highlightData.description || '',
      startTime: highlightData.startTime || 0,
      endTime: highlightData.endTime || 0,
      duration: (highlightData.endTime || 0) - (highlightData.startTime || 0),
      type: highlightData.type || 'epic_moment',
      difficulty: highlightData.difficulty || 'medium',
      videoUrl: highlightData.videoUrl || '',
      thumbnailUrl: highlightData.thumbnailUrl || '',
      autoGenerated: highlightData.autoGenerated || false,
      createdAt: Date.now(),
      isPublic: highlightData.isPublic || false,
      views: 0,
      likes: 0,
      shares: 0,
      comments: []
    };

    this.highlights.set(highlight.id, highlight);
    this.saveToStorage();
    return highlight;
  }

  getHighlight(highlightId: string): Highlight | undefined {
    return this.highlights.get(highlightId);
  }

  getHighlights(userId: string): Highlight[] {
    return Array.from(this.highlights.values()).filter(h => h.userId === userId);
  }

  getHighlightsByReplay(replayId: string): Highlight[] {
    return Array.from(this.highlights.values()).filter(h => h.replayId === replayId);
  }

  getPublicHighlights(): Highlight[] {
    return Array.from(this.highlights.values()).filter(h => h.isPublic);
  }

  deleteHighlight(highlightId: string): boolean {
    return this.highlights.delete(highlightId);
  }

  likeHighlight(highlightId: string): void {
    const highlight = this.highlights.get(highlightId);
    if (highlight) {
      highlight.likes++;
      this.saveToStorage();
    }
  }

  unlikeHighlight(highlightId: string): void {
    const highlight = this.highlights.get(highlightId);
    if (highlight && highlight.likes > 0) {
      highlight.likes--;
      this.saveToStorage();
    }
  }

  addComment(highlightId: string, comment: HighlightComment): void {
    const highlight = this.highlights.get(highlightId);
    if (highlight) {
      highlight.comments.push(comment);
      this.saveToStorage();
    }
  }

  // Clip Management
  createClip(userId: string, clipData: Partial<Clip>): Clip {
    const clip: Clip = {
      id: `clip_${userId}_${Date.now()}`,
      highlightId: clipData.highlightId || '',
      userId,
      title: clipData.title || 'Clip',
      description: clipData.description || '',
      duration: clipData.duration || 0,
      startFrame: clipData.startFrame || 0,
      endFrame: clipData.endFrame || 0,
      videoUrl: clipData.videoUrl || '',
      thumbnailUrl: clipData.thumbnailUrl || '',
      format: clipData.format || 'mp4',
      resolution: clipData.resolution || '1080p',
      createdAt: Date.now(),
      isPublic: clipData.isPublic || false,
      views: 0,
      likes: 0,
      downloads: 0
    };

    this.clips.set(clip.id, clip);
    this.saveToStorage();
    return clip;
  }

  getClip(clipId: string): Clip | undefined {
    return this.clips.get(clipId);
  }

  getClips(userId: string): Clip[] {
    return Array.from(this.clips.values()).filter(c => c.userId === userId);
  }

  getClipsByHighlight(highlightId: string): Clip[] {
    return Array.from(this.clips.values()).filter(c => c.highlightId === highlightId);
  }

  deleteClip(clipId: string): boolean {
    return this.clips.delete(clipId);
  }

  downloadClip(clipId: string): void {
    const clip = this.clips.get(clipId);
    if (clip) {
      clip.downloads++;
      this.saveToStorage();
    }
  }

  // Playback Management
  startPlayback(replayId: string, userId: string): PlaybackSession {
    const session: PlaybackSession = {
      id: `session_${replayId}_${userId}_${Date.now()}`,
      replayId,
      userId,
      currentFrame: 0,
      currentTime: 0,
      isPlaying: false,
      playbackSpeed: 1,
      volume: 100,
      subtitles: false,
      startedAt: Date.now(),
      totalWatchTime: 0,
      viewedFrames: []
    };

    this.playbackSessions.set(session.id, session);
    this.saveToStorage();
    return session;
  }

  updatePlaybackPosition(sessionId: string, frame: number, time: number): void {
    const session = this.playbackSessions.get(sessionId);
    if (session) {
      session.currentFrame = frame;
      session.currentTime = time;
      if (!session.viewedFrames.includes(frame)) {
        session.viewedFrames.push(frame);
      }
      session.totalWatchTime = time;
      this.saveToStorage();
    }
  }

  setPlaybackSpeed(sessionId: string, speed: number): void {
    const session = this.playbackSessions.get(sessionId);
    if (session) {
      session.playbackSpeed = Math.max(0.25, Math.min(2, speed));
      this.saveToStorage();
    }
  }

  setVolume(sessionId: string, volume: number): void {
    const session = this.playbackSessions.get(sessionId);
    if (session) {
      session.volume = Math.max(0, Math.min(100, volume));
      this.saveToStorage();
    }
  }

  getPlaybackSession(sessionId: string): PlaybackSession | undefined {
    return this.playbackSessions.get(sessionId);
  }

  endPlayback(sessionId: string): void {
    this.playbackSessions.delete(sessionId);
    this.saveToStorage();
  }

  // Analytics
  recordView(replayId: string, watchTime: number): void {
    const replay = this.replays.get(replayId);
    if (replay) {
      replay.views++;
      const analytics = this.analytics.get(replayId);
      if (analytics) {
        analytics.totalViews++;
        analytics.avgWatchTime = (analytics.avgWatchTime * (analytics.totalViews - 1) + watchTime) / analytics.totalViews;
        const replay_obj = this.replays.get(replayId)!;
        analytics.completionRate = replay_obj.duration > 0 ? (watchTime / replay_obj.duration) * 100 : 0;
      }
      this.saveToStorage();
    }
  }

  getAnalytics(replayId: string): ReplayAnalytics | undefined {
    return this.analytics.get(replayId);
  }

  // Highlight AI Configuration
  setHighlightAIConfig(userId: string, config: Partial<HighlightAI>): HighlightAI {
    let aiConfig = this.highlightAIConfigs.get(userId) || {
      minIntensity: 0.5,
      detectGoals: true,
      detectSaves: true,
      detectTackles: true,
      detectSkillMoves: true,
      minDuration: 5,
      maxDuration: 60
    };

    Object.assign(aiConfig, config);
    this.highlightAIConfigs.set(userId, aiConfig);
    this.saveToStorage();
    return aiConfig;
  }

  getHighlightAIConfig(userId: string): HighlightAI {
    return this.highlightAIConfigs.get(userId) || {
      minIntensity: 0.5,
      detectGoals: true,
      detectSaves: true,
      detectTackles: true,
      detectSkillMoves: true,
      minDuration: 5,
      maxDuration: 60
    };
  }

  // Auto-Generation
  autoGenerateHighlights(replayId: string, userId: string): Highlight[] {
    const replay = this.replays.get(replayId);
    if (!replay) return [];

    const aiConfig = this.getHighlightAIConfig(userId);
    const highlights: Highlight[] = [];

    // Analyze events for highlights
    replay.events.forEach((event, index) => {
      if (aiConfig.detectGoals && event.type === 'goal') {
        const startTime = Math.max(0, event.timestamp - 3);
        const endTime = Math.min(replay.duration, event.timestamp + 5);
        
        const highlight = this.createHighlight(userId, {
          replayId,
          title: `Goal - ${event.player}`,
          description: `Goal scored by ${event.player}`,
          startTime,
          endTime,
          type: 'goal',
          difficulty: 'hard',
          autoGenerated: true,
          isPublic: false
        });
        highlights.push(highlight);
      }

      if (aiConfig.detectSaves && event.type === 'tackle') {
        const startTime = Math.max(0, event.timestamp - 2);
        const endTime = Math.min(replay.duration, event.timestamp + 3);
        
        const highlight = this.createHighlight(userId, {
          replayId,
          title: `Save - ${event.player}`,
          description: `Great save by ${event.player}`,
          startTime,
          endTime,
          type: 'save',
          difficulty: 'medium',
          autoGenerated: true,
          isPublic: false
        });
        highlights.push(highlight);
      }

      if (aiConfig.detectSkillMoves && event.type === 'shot') {
        const startTime = Math.max(0, event.timestamp - 2);
        const endTime = Math.min(replay.duration, event.timestamp + 2);
        
        const highlight = this.createHighlight(userId, {
          replayId,
          title: `Epic Moment - ${event.player}`,
          description: `Amazing shot by ${event.player}`,
          startTime,
          endTime,
          type: 'epic_moment',
          difficulty: 'medium',
          autoGenerated: true,
          isPublic: false
        });
        highlights.push(highlight);
      }
    });

    return highlights;
  }

  // Storage
  private saveToStorage(): void {
    try {
      const data = {
        replays: Array.from(this.replays.entries()),
        highlights: Array.from(this.highlights.entries()),
        clips: Array.from(this.clips.entries()),
        playbackSessions: Array.from(this.playbackSessions.entries()),
        analytics: Array.from(this.analytics.entries()),
        highlightAIConfigs: Array.from(this.highlightAIConfigs.entries())
      };
      localStorage.setItem('replayEngine:global', JSON.stringify(data));
    } catch (error) {
      console.error('Error saving replay data:', error);
    }
  }

  private loadFromStorage(): void {
    try {
      const data = JSON.parse(localStorage.getItem('replayEngine:global') || '{}');
      if (data.replays) this.replays = new Map(data.replays);
      if (data.highlights) this.highlights = new Map(data.highlights);
      if (data.clips) this.clips = new Map(data.clips);
      if (data.playbackSessions) this.playbackSessions = new Map(data.playbackSessions);
      if (data.analytics) this.analytics = new Map(data.analytics);
      if (data.highlightAIConfigs) this.highlightAIConfigs = new Map(data.highlightAIConfigs);
    } catch (error) {
      console.error('Error loading replay data:', error);
    }
  }

  // Helper Methods
  getStats(userId: string) {
    const userReplays = this.getReplays(userId);
    const userHighlights = this.getHighlights(userId);
    const userClips = this.getClips(userId);

    const totalViews = userReplays.reduce((sum, r) => sum + r.views, 0);
    const totalHighlightViews = userHighlights.reduce((sum, h) => sum + h.views, 0);
    const totalLikes = userHighlights.reduce((sum, h) => sum + h.likes, 0);

    return {
      totalReplays: userReplays.length,
      totalHighlights: userHighlights.length,
      totalClips: userClips.length,
      totalViews,
      totalHighlightViews,
      totalLikes,
      publicReplays: userReplays.filter(r => r.isPublic).length,
      publicHighlights: userHighlights.filter(h => h.isPublic).length
    };
  }
}

// Export singleton instance
export const replayEngine = new ReplayEngineService();
